### ISSUE TITLE
能否增加光源的方向？

### ISSUE THREAD

**Issue by sbcdba** [Haoming02/sd-forge-ic-light#11]
像ic-light原版与https://github.com/QodiCat/IC-Light-SD-WebUI那样，增加前后左右光源方向？

**Comment by Haoming02** [comment]
光源方向 有在 **img2img**模式 裡。

<p align="center">
<img src="https://github.com/user-attachments/assets/cefcc284-2f95-4d9d-9d4a-139d5370e39b">
</p>
