### ISSUE TITLE
Not seeing Ic-light in Reforge UI

### ISSUE THREAD

**Issue by koopa990** [Haoming02/sd-forge-ic-light#13]
I followed your instruction with exactness. Is there something wrong?>

**Comment by Haoming02** [comment]
Would be helpful if you provide the error logs...

**Comment by koopa990** [comment]
> Would be helpful if you provide the error logs...

Where do I find it exactly? From the console window or within .txt file?

**Comment by Haoming02** [comment]
Console

**Comment by koopa990** [comment]
> Console

![image](https://github.com/user-attachments/assets/dffc5dc6-1a0c-4970-889a-2389ac86887e)
I do not see anything relating to **ic-light**.

**Comment by Haoming02** [comment]
Hmm... try doing a clean install I guess?

I just tested right now, and it worked with all 3 `main`, `dev`, `dev2` branches just fine

**Comment by koopa990** [comment]
> Hmm... try doing a clean install I guess?
> 
> I just tested right now, and it worked with all 3 `main`, `dev`, `dev2` branches just fine

Reinstalling ic-light or the whole Reforge?

Also, where would ic-light be found in the webUI?

**Comment by Haoming02** [comment]
> Reinstalling ic-light or the whole Reforge?

The whole Webui; or try disabling other Extensions, though I don't think there would be any conflicts.

> Also, where would ic-light be found in the webUI?

Just like every other Extension, under the parameters.

**Comment by koopa990** [comment]
> > Reinstalling ic-light or the whole Reforge?
> 
> The whole Webui; or try disabling other Extensions, though I don't think there would be any conflicts.
> 
> > Also, where would ic-light be found in the webUI?
> 
> Just like every other Extension, under the parameters.

Can't you make, like, a installable .git for the webUI to install it?

**Comment by Haoming02** [comment]
wdym

**Comment by koopa990** [comment]
![image](https://github.com/user-attachments/assets/2b2f0b6e-6429-4cc3-a7b8-4ece8df4a2e0)

Something like this

**Comment by Haoming02** [comment]
Just paste the url into the field shown in the screenshot, the same way with most if not all other Extensions.

<p align="center">
<img src="https://github.com/user-attachments/assets/73da5c88-5592-42df-9c19-979838f1ef83">
</p>

**Comment by koopa990** [comment]
Let me install this method.

**Comment by koopa990** [comment]
Okay! I got to work and appear.

And, oh... I must have misunderstood the intention of this extension, or I am using this incorrectly. I thought this can transform existing image into different lighting, and also generate new image with modified lighting?

**Comment by Haoming02** [comment]
> I thought this can transform existing image into different lighting, and also generate new image with modified lighting?

Yes?

**Comment by koopa990** [comment]
Nevermind. Is there other similar extension that supports Pony SDXL?

**Comment by Haoming02** [comment]
Everyone has been hoping for <ins>lllyasviel</ins> to release an IC-Light model for SDXL. But he's working on one for Flux instead right now... 

Probably in the distant future?

**Comment by koopa990** [comment]
I see...

I also tested out the lora model "darker than Pony", which does not work 100% of the time. I guess I am out of options
