### ISSUE TITLE
Why do I get the same error on reforge (the code has been updated), but it works perfectly on Forge?

### ISSUE THREAD

**Issue by pinea00** [Haoming02/sd-forge-ic-light#6]
Why do I get the same error on reforge (the code has been updated), but it works perfectly on Forge?
I do'nt install LayerDiffuse for forge or reforge.
WARNING:root:WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
Moving model(s) has taken 0.62 seconds
0%| | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
File "S:\reForge\modules_forge\main_thread.py", line 37, in loop
task.work()
File "S:\reForge\modules_forge\main_thread.py", line 26, in work
self.result = self.func(*self.args, **self.kwargs)
File "S:\reForge\modules\img2img.py", line 235, in img2img_function
processed = process_images(p)
File "S:\reForge\modules\processing.py", line 856, in process_images
res = process_images_inner(p)
File "S:\reForge\modules\processing.py", line 1007, in process_images_inner
samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
File "S:\reForge\modules\processing.py", line 1828, in sample
samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
File "S:\reForge\modules\sd_samplers_kdiffusion.py", line 207, in sample_img2img
samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
File "S:\reForge\modules\sd_samplers_common.py", line 274, in launch_sampling
return func()
File "S:\reForge\modules\sd_samplers_kdiffusion.py", line 207, in
samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
File "S:\venvzluda\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "S:\reForge\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
denoised = model(x, sigmas[i] * s_in, **extra_args)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self.call_impl(*args, **kwargs)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1541, in call_impl
return forward_call(*args, **kwargs)
File "S:\reForge\modules\sd_samplers_cfg_denoiser.py", line 225, in forward
denoised = sampling_function(model, x, sigma, uncond_patched, cond_patched, cond_scale, model_options, seed)
File "S:\reForge\ldm_patched\modules\samplers.py", line 299, in sampling_function
cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
File "S:\reForge\ldm_patched\modules\samplers.py", line 260, in calc_cond_uncond_batch
output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
File "S:\stable-diffusion-webui\extensions\sd-forge-ic-light\lib_iclight\ic_light_nodes.py", line 61, in wrapper_func
return existing_wrapper(unet_apply, params=apply_c_concat(params))
File "S:\stable-diffusion-webui\extensions\sd-forge-ic-light\lib_iclight\ic_light_nodes.py", line 53, in unet_dummy_apply
return unet_apply(x=params["input"], t=params["timestep"], **params["c"])
File "S:\reForge\ldm_patched\modules\model_base.py", line 90, in apply_model
model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "S:\reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 886, in forward
h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
File "S:\reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 61, in forward_timestep_embed
x = layer(x)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "S:\reForge\ldm_patched\modules\ops.py", line 114, in forward
return super().forward(*args, **kwargs)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
return self._conv_forward(input, self.weight, self.bias)
File "S:\venvzluda\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead
*** Error completing request
*** Arguments: ('task(wfpegk5t343l3v7)', <gradio.routes.Request object at 0x000001BC852262F0>, 0, '1 girl, bridal dress, black hair, at the seaside, sunset', '', [], <PIL.Image.Image image mode=RGBA size=768x768 at 0x1BC861DB220>, None, None, None, None, None, None, 4, 0, 1, 1, 1, 2, 1.5, 1, 0.0, 768, 768, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', 0, False, 1, 0.5, 4, 0, 0.5, 2, 8, 'DPM++ 2M SDE', 'Turbo', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, False, False, False, 'base', 'None', 3, 5, 2, 0, 0.1, 3, 5, False, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001BC7FC19D20>, True, 'iclight_sd15_fc_unet_ldm', 'Right Light', 'Use Background Image', array([[[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]],

*** [[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]],

*** [[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]],

*** ...,

*** [[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]],

*** [[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]],

*** [[ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** [ 0, 0, 0, 255],
*** ...,
*** [254, 254, 254, 255],
*** [254, 254, 254, 255],
*** [255, 255, 255, 255]]], dtype=uint8), None, True, 'u2net_human_seg', 225, 16, 16, False, False, 3, False, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, '* CFG Scale should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '

Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8

', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '
Will upscale the image by the selected scale factor; use width and height sliders to set tile size

', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, '
Will upscale the image depending on the selected target size type

', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
File "S:\reForge\modules\call_queue.py", line 74, in f
res = list(func(*args, **kwargs))
TypeError: 'NoneType' object is not iterable

**Comment by Haoming02** [comment]
Welp, can't recreate it. Both `txt2img` and `img2img` worked for me.

Maybe try disabling other Extensions first?

**Comment by pinea00** [comment]
I tried reinstalling VENV, deleting all data and git clone again, resetting all configurations and caches, and leaving only one IC-light extension. All to no work. Maybe it’s because I use zluda and comfyui (reforge backend code) program. It may be due to code incompatibility (old forge works normally without using anything but directly installing it)

**Comment by Haoming02** [comment]
Forgot to ask, do you see `calculate_weight Patched!` in the console when launching the Webui?

**Comment by pinea00** [comment]
完整的console,沒看到～A卡極限大概就這樣吧
------------------
venv "VENV\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.2-v1.10.1RC-1.10.1
Commit hash: <none>
Launching Web UI with arguments: --theme dark --api --autolaunch --use-cpu gfpgan codeformer --zluda
Total VRAM 8176 MB, total RAM 32606 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 [ZLUDA] : native
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
ControlNet preprocessor location: S:\stable-diffusion-webui\models\ControlNetPreprocessor
watermark logo: S:\stable-diffusion-webui\extensions\sd-webui-facefusion-dev\watermark.png
[-] sd-webui-facefusion initialized. FaceFusion 2.1.2
2024-08-14 11:15:09,053 - AnimateDiff - INFO - AnimateDiff Hooking i2i_batch
Loading model realisticVisionV60B1_v51VAE.safetensors [15012c538f] (1 of 1)
Loading weights [15012c538f] from S:\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV60B1_v51VAE.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8008.2919921875
[Memory Management] Model Memory (MB) =  454.20703506469727
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  6530.084957122803
Moving model(s) has taken 0.07 seconds
Model realisticVisionV60B1_v51VAE.safetensors [15012c538f] loaded in 4.5s (load weights from disk: 0.1s, forge load real models: 3.5s, calculate empty prompt: 0.8s).
2024-08-14 11:15:13,747 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 30.6s (prepare environment: 6.3s, import torch: 4.8s, import gradio: 2.1s, setup paths: 3.2s, initialize shared: 0.3s, other imports: 1.3s, load scripts: 7.0s, create ui: 5.2s, gradio launch: 0.2s, add APIs: 0.3s).
S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Translating prompt to English from 中文
Initial prompt:cinematic photo 1 girl, bridal dress, dark hair, beach by the sea, sunset . 35mm photograph, film, bokeh, professional, 4k, highly detailed
Translated prompt:cinematic photo 1 girl, bridal dress, dark hair, beach by the sea, sunset . 35mm photograph, film, bokeh, professional, 4k, highly detailed, spend time:0.0
Translating negative prompt to English from 中文
Initial negative prompt:drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly
Translated negative prompt:drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly, spend time:0.000997304916381836
To load target model AutoencoderKL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7660.08544921875
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  6476.528367996216
Moving model(s) has taken 0.05 seconds
To load target model AutoencoderKL
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  5846.02978515625
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4822.02978515625
Moving model(s) has taken 0.00 seconds
To load target model BaseModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  5849.40478515625
[Memory Management] Model Memory (MB) =  1639.4137649536133
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3185.9910202026367
WARNING:root:WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
Moving model(s) has taken 0.60 seconds
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\img2img.py", line 235, in img2img_function
    processed = process_images(p)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\processing.py", line 822, in process_images
    res = process_images_inner(p)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\processing.py", line 971, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\processing.py", line 1789, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\sd_samplers_kdiffusion.py", line 207, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\sd_samplers_common.py", line 274, in launch_sampling
    return func()
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\sd_samplers_kdiffusion.py", line 207, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\sd_samplers_cfg_denoiser.py", line 225, in forward
    denoised = sampling_function(model, x, sigma, uncond_patched, cond_patched, cond_scale, model_options, seed)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\modules\samplers.py", line 299, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\modules\samplers.py", line 260, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "S:\stable-diffusion-webui\extensions\sd-forge-ic-light\lib_iclight\ic_light_nodes.py", line 61, in wrapper_func
    return existing_wrapper(unet_apply, params=apply_c_concat(params))
  File "S:\stable-diffusion-webui\extensions\sd-forge-ic-light\lib_iclight\ic_light_nodes.py", line 53, in unet_dummy_apply
    return unet_apply(x=params["input"], t=params["timestep"], **params["c"])
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\modules\model_base.py", line 90, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 886, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 61, in forward_timestep_embed
    x = layer(x)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\ldm_patched\modules\ops.py", line 114, in forward
    return super().forward(*args, **kwargs)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\VENV\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead
*** Error completing request
*** Arguments: ('task(hqzvhdihiigzwap)', <gradio.routes.Request object at 0x0000025E0743E7A0>, 0, 'cinematic photo 1 girl, bridal dress, dark hair, beach by the sea, sunset . 35mm photograph, film, bokeh, professional, 4k, highly detailed', 'drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly', [], <PIL.Image.Image image mode=RGBA size=768x768 at 0x25E0644BA00>, None, None, None, None, None, None, 4, 0, 1, 1, 1, 2, 1.5, 1, 0.0, 768, 768, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', 0, False, 1, 0.5, 4, 0, 0.5, 2, 8, 'DPM++ 2M SDE', 'Turbo', False, '', 0.8, -1, False, -1, 0, 0, 0, False, True, False, False, False, 'base', 'None', 3, 5, 2, 0, 0.1, 3, 5, False, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000025E0743DA80>, True, 'iclight_sd15_fc_unet_ldm', 'Right Light', 'Use Background Image', array([[[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]],
***
***        [[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]],
***
***        [[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]],
***
***        ...,
***
***        [[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]],
***
***        [[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]],
***
***        [[  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         [  0,   0,   0, 255],
***         ...,
***         [254, 254, 254, 255],
***         [254, 254, 254, 255],
***         [255, 255, 255, 255]]], dtype=uint8), None, True, 'u2net_human_seg', 225, 16, 16, True, False, 3, True, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0.7, False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "S:\TEST-CODE\stable-diffusion-webui-reForge-main\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

**Comment by Haoming02** [comment]
Wait, are you using the `dev_upstream` branch of reForge?

**Comment by Haoming02** [comment]
Anyway, made the patch to always be applied. Should work for old Forge, `main` reForge, and `dev_upstream` reForge now

**Comment by pinea00** [comment]
The two latest codes of reForge in main and dev_upstream can work normally using zluda test. 
Thank you.
