### ISSUE TITLE
new forge compatibility

### ISSUE THREAD

**Issue by dan4ik94** [Haoming02/sd-forge-ic-light#8]
I guess some modules have been moved/renamed.

```
*** Error loading script: ic_light_script.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\webui_forge_cu121_torch231\webui\extensions\sd-forge-ic-light\scripts\ic_light_script.py", line 12, in <module>
        import lib_iclight.patch_weight
      File "D:\webui_forge_cu121_torch231\webui\extensions\sd-forge-ic-light\lib_iclight\patch_weight.py", line 8, in <module>
        from ldm_patched.modules.model_management import cast_to_device
    ModuleNotFoundError: No module named 'ldm_patched'

**Comment by Haoming02** [comment]
The new Forge now has built-in [IC-Light](https://github.com/lllyasviel/stable-diffusion-webui-forge/tree/main/extensions-builtin/forge_space_iclight) in the **Space**s thingy.

So this Extension is no longer needed I presume

**Comment by dan4ik94** [comment]
> The new Forge now has built-in [IC-Light](https://github.com/lllyasviel/stable-diffusion-webui-forge/tree/main/extensions-builtin/forge_space_iclight) in the **Space**s thingy.
> 
> So this Extension is no longer needed I presume

Yes, but it downloads and runs the default gradio app from huggingface. We can't change the checkpoint, parameters and it lacks a lot of features.

It would be really cool and handy to fix the current extension.

**Comment by Haoming02** [comment]
Hmm, I'll look into it then

**Comment by dan4ik94** [comment]
> Hmm, I'll look into it then

Thank you.

**Comment by sbcdba** [comment]
> The new Forge now has built-in [IC-Light](https://github.com/lllyasviel/stable-diffusion-webui-forge/tree/main/extensions-builtin/forge_space_iclight) in the **Space**s thingy.
> 
> So this Extension is no longer needed I presume

1、Space's [IC-Light] not has FBC.
2、Space's [IC-Light] not has Restore Details.

**Comment by Haoming02** [comment]
Hello, please check out the latest commit~

**Comment by dan4ik94** [comment]
> Hello, please check out the latest commit~

![Strip 1 (1)](https://github.com/user-attachments/assets/a06a0d98-7d49-4a99-bb7c-a4f2d1c530cd)

**Comment by sbcdba** [comment]
> Hello, please check out the latest commit~

thank you，in new Forge working very good.
